name: .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: List files
        run: ls -R
      - name: Restore dependencies
        run: dotnet restore CandidatesApp.sln
      - name: Build
        run: dotnet build CandidatesApp.sln --no-restore
      - name: Test
        run: dotnet test CandidatesApp.sln --no-build --verbosity normal
